# Generated by Django 3.1.3 on 2020-11-27 13:35

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0002_auto_20201127_1016'),
    ]

    operations = [
        migrations.AddField(
            model_name='nota',
            name='IRRF_Day_Trade',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='IRRF Day Trade'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='nota',
            name='IRRF_Final',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='IRRF Final'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='nota',
            name='Lucro_Day_Trade',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Lucro Day Trade'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='nota',
            name='corretagem',
            field=models.DecimalField(decimal_places=2, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='nota',
            name='emolumentos',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Emolumento B3'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='nota',
            name='identificador',
            field=models.CharField(max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='nota',
            name='tx_liquida_CBLC',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Taxa Líquida CBLC'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='nota',
            name='data',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
