# Generated by Django 3.1.3 on 2020-11-27 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0003_auto_20201127_1035'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nota',
            name='data',
            field=models.DateField(),
        ),
    ]
