# Generated by Django 3.1.3 on 2020-12-13 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0011_auto_20201205_2305'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cotacao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fechamento_ajustado', models.CharField(blank=True, max_length=255)),
                ('fechamento', models.CharField(blank=True, max_length=255)),
                ('abertura', models.CharField(blank=True, max_length=255)),
                ('alto', models.CharField(blank=True, max_length=255)),
                ('baixo', models.CharField(blank=True, max_length=255)),
                ('volume', models.CharField(blank=True, max_length=255)),
                ('data', models.DateField(blank=True)),
            ],
        ),
    ]
