# Generated by Django 3.1.3 on 2020-12-14 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0012_cotacao'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cotacao',
            name='abertura',
        ),
        migrations.RemoveField(
            model_name='cotacao',
            name='alto',
        ),
        migrations.RemoveField(
            model_name='cotacao',
            name='baixo',
        ),
        migrations.RemoveField(
            model_name='cotacao',
            name='data',
        ),
        migrations.RemoveField(
            model_name='cotacao',
            name='fechamento',
        ),
        migrations.RemoveField(
            model_name='cotacao',
            name='volume',
        ),
    ]
