# Generated by Django 3.1.3 on 2020-12-14 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0013_auto_20201214_1029'),
    ]

    operations = [
        migrations.AddField(
            model_name='cotacao',
            name='ativo',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
