# Generated by Django 3.1.3 on 2020-12-14 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0014_cotacao_ativo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cotacao',
            name='fechamento_ajustado',
            field=models.CharField(blank=True, default=0, max_length=255),
        ),
    ]
