# Generated by Django 3.1.3 on 2020-12-19 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0017_auto_20201214_1739'),
    ]

    operations = [
        migrations.AddField(
            model_name='cotacao',
            name='acao',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
