# Generated by Django 3.1.3 on 2020-12-19 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0018_cotacao_acao'),
    ]

    operations = [
        migrations.AddField(
            model_name='cotacao',
            name='variacao_1',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='cotacao',
            name='variacao_2',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
