# Generated by Django 3.1.3 on 2020-12-19 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0019_auto_20201219_1636'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cotacao',
            name='variacao_1',
            field=models.CharField(blank=True, default=0.0, max_length=255),
        ),
        migrations.AlterField(
            model_name='cotacao',
            name='variacao_2',
            field=models.CharField(blank=True, default=0.0, max_length=255),
        ),
    ]
