# Generated by Django 3.1.3 on 2020-12-21 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0021_auto_20201219_2112'),
    ]

    operations = [
        migrations.AddField(
            model_name='cotacao',
            name='status_fechado_aberto',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
