# Generated by Django 3.1.3 on 2020-12-21 22:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
from django.contrib.auth.models import User


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cadastros', '0022_cotacao_status_fechado_aberto'),
    ]

    operations = [
        migrations.AddField(
            model_name='nota',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='auth.user', verbose_name='usuário'),
            preserve_default=False,
        ),
    ]
