# Generated by Django 3.1.3 on 2020-12-21 23:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0023_nota_usuer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='nota',
            old_name='usuer',
            new_name='user',
        ),
    ]
