# Generated by Django 3.1.3 on 2020-12-25 18:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0026_ativo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ativo',
            name='quantidade',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
