# Generated by Django 3.1.3 on 2020-12-28 14:48

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0027_auto_20201225_1550'),
    ]

    operations = [
        migrations.AddField(
            model_name='nota',
            name='corretora',
            field=models.CharField(default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
    ]
