# Generated by Django 3.1.3 on 2020-12-28 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0030_remove_nota_corretora'),
    ]

    operations = [
        migrations.AddField(
            model_name='nota',
            name='corretora',
            field=models.CharField(blank=True, max_length=250, default='Rico'),
        ),
    ]
