# Generated by Django 3.1.3 on 2020-12-28 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0032_auto_20201228_1218'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nota',
            name='corretora',
            field=models.CharField(blank=True, max_length=250),
        ),
    ]
